# Use postgres/example user/password credentials
version: '3.1'

services:
  calendarapp-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example